var ccb_resources = [
    {type:'ccbi', src:"startgame.ccbi"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"player.png"},
    {type:'image', src:"tmw_desert_spacing.png"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"transparent.png"},
    {type:'image', src:"clickme.png"},
    {type:'ccbi', src:"gamelevels.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"scene1.png"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
